const assert = require('node:assert/strict')
const fs = require('node:fs')
const vm = require('node:vm')
const context = {}
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../js/mobile-app.js'), 'utf8'), context)
const metrics = context.mobileViewportMetrics
const expanded = metrics({ scale: 1, height: 640, offsetTop: 0 }, 812, 44, 34)
const collapsed = metrics({ scale: 1, height: 760, offsetTop: 0 }, 812, 44, 34)
assert.equal(expanded.height, 640)
assert.equal(collapsed.height, 760)
assert.ok(expanded.homeScale < collapsed.homeScale)
for (const height of [320, 480, 568, 640, 812]) {
    const result = metrics({ scale: 1, height, offsetTop: 0 }, 812, 44, 34)
    assert.ok(result.homeScale * 640 + 44 + 34 + 40 <= height + 0.001)
}
assert.equal(metrics({ scale: 1, height: 360, offsetTop: 150 }, 812).top, 150)
assert.equal(metrics({ scale: 2, height: 320, offsetTop: 80 }, 812).height, 812)
assert.equal(metrics(null, 568).height, 568)
assert.equal(metrics({ scale: 1, height: 900, offsetTop: 0 }, 900).homeScale, 1)
const points = [0, 100, 200]
const target = [4, 96, 204]
context.mobileTriangleStep(points, target, 16)
assert.ok(points[0] > 0 && points[0] < 4)
assert.ok(points[1] < 100 && points[1] > 96)
for (let frame = 0; frame < 240; frame++) context.mobileTriangleStep(points, target, 16)
assert.ok(Math.abs(points[0] - 4) < 0.1)
assert.ok(Math.abs(points[1] - 96) < 0.1)
console.log('Mobile layout: toolbar, safe areas, keyboard, zoom, fallback and smooth triangle interpolation passed.')
const mobileCSS = fs.readFileSync(require('node:path').join(__dirname, '../css/mobile.css'), 'utf8')
assert.match(mobileCSS, /html\.m-document-scroll\s*\{[^}]*overflow: visible;/)
assert.match(mobileCSS, /html\.m-document-scroll #mobileApp\s*\{[^}]*position: static;[^}]*background: transparent;[^}]*overflow-x: clip;[^}]*overflow-y: visible;/)
assert.doesNotMatch(mobileCSS, /m-detail-banner[^{}]*\{[^}]*position:\s*(fixed|sticky)/)
assert.doesNotMatch(mobileCSS, /m-detail-banner::(?:before|after)/)
assert.match(mobileCSS, /\.m-article\.m-has-banner\s*\{\s*padding-top: 0;/)
const mobileSource = fs.readFileSync(require('node:path').join(__dirname, '../js/mobile-app.js'), 'utf8')
assert.doesNotMatch(mobileSource, /banner\.remove\(\)|bannerHTML/)
assert.match(mobileSource, /doc\.body\.innerHTML \+ toolbar\(post, next\) \+ '<\/main>'/)
console.log('Article edges: first-version document flow, zero banner top gap and inline comment toolbar passed.')
const indexHTML = fs.readFileSync(require('node:path').join(__dirname, '../index.html'), 'utf8')
const aboutHTML = fs.readFileSync(require('node:path').join(__dirname, '../about/index.html'), 'utf8')
const releaseVersion = aboutHTML.match(/网站版本：(\d{8}-\d{2})/)[1]
assert.ok(indexHTML.includes('/css/mobile.css?v=' + releaseVersion))
assert.ok(indexHTML.includes('/js/mobile-app.js?v=' + releaseVersion))
assert.match(mobileSource, /load\('\/about\/index\.html\?v=' \+ encodeURIComponent\(jsVersion\)\)/)
console.log('About release version matches CSS and JS resource versions: ' + releaseVersion)
