const assert = require('node:assert/strict')
const fs = require('node:fs')
const vm = require('node:vm')
const context = {}
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../js/mobile-app.js'), 'utf8'), context)
const metrics = context.mobileViewportMetrics
const expanded = metrics({ scale: 1, height: 640, offsetTop: 0 }, 812, 44, 34)
const collapsed = metrics({ scale: 1, height: 760, offsetTop: 0 }, 812, 44, 34)
assert.equal(expanded.height, 640)
assert.equal(collapsed.height, 760)
assert.ok(expanded.homeScale < collapsed.homeScale)
for (const height of [320, 480, 568, 640, 812]) {
    const result = metrics({ scale: 1, height, offsetTop: 0 }, 812, 44, 34)
    assert.ok(result.homeScale * 640 + 44 + 34 + 40 <= height + 0.001)
}
assert.equal(metrics({ scale: 1, height: 360, offsetTop: 150 }, 812).height, 360)
assert.equal(metrics({ scale: 2, height: 320, offsetTop: 80 }, 812).height, 812)
assert.equal(metrics(null, 568).height, 568)
assert.equal(metrics({ scale: 1, height: 900, offsetTop: 0 }, 900).homeScale, 1)
const points = [0, 100, 200]
const target = [4, 96, 204]
context.mobileTriangleStep(points, target, 16)
assert.ok(points[0] > 0 && points[0] < 4)
assert.ok(points[1] < 100 && points[1] > 96)
for (let frame = 0; frame < 240; frame++) context.mobileTriangleStep(points, target, 16)
assert.ok(Math.abs(points[0] - 4) < 0.1)
assert.ok(Math.abs(points[1] - 96) < 0.1)
console.log('Mobile layout: home sizing, safe areas, zoom, fallback and smooth triangle interpolation passed.')
const mobileCSS = fs.readFileSync(require('node:path').join(__dirname, '../css/mobile.css'), 'utf8')
assert.match(mobileCSS, /(?:^|\n)html\s*\{[^}]*height: auto;/)
assert.match(mobileCSS, /(?:^|\n)body\s*\{[^}]*background: white;/)
assert.match(mobileCSS, /(?:^|\n)#mobileApp\s*\{[^}]*min-height: 100svh;[^}]*overflow-x: clip;/)
assert.doesNotMatch(mobileCSS, /m-document-scroll|--m-viewport-(height|top)/)
assert.doesNotMatch(mobileCSS, /(?:^|\n)#mobileApp\s*\{[^}]*(?:position: fixed|height:\s*(?:100%|var\())/)
assert.match(mobileCSS, /\.m-home\s*\{[^}]*height: var\(--m-home-height, 100svh\);[^}]*overflow: hidden;/)
assert.doesNotMatch(mobileCSS, /\.m-detail > main\s*\{[^}]*overflow/)
assert.match(mobileCSS, /#mobileApp \.m-article > \.essay-title, #mobileApp \.m-article > \._date\s*\{\s*width: auto;/)
assert.doesNotMatch(mobileCSS, /m-detail-banner[^{}]*\{[^}]*position:\s*(fixed|sticky)/)
assert.doesNotMatch(mobileCSS, /m-detail-banner::(?:before|after)/)
assert.match(mobileCSS, /\.m-article\s*\{\s*padding: 54px/)
assert.match(mobileCSS, /\.m-article:has\(> \._banner\)\s*\{\s*padding-top: 0;/)
assert.match(mobileCSS, /\.m-article\s+\._banner::after\s*\{\s*content: none;/)
assert.doesNotMatch(mobileCSS, /\.m-article\s+\._banner\s*\{[^}]*position:\s*(?:fixed|sticky)/)
const mobileSource = fs.readFileSync(require('node:path').join(__dirname, '../js/mobile-app.js'), 'utf8')
assert.doesNotMatch(mobileSource, /banner\.remove\(\)|bannerHTML/)
assert.match(mobileSource, /doc\.body\.innerHTML \+ toolbar\(post, next\) \+ '<\/main>'/)
assert.doesNotMatch(mobileSource, /m-document-scroll|root\.style\.setProperty|--m-viewport-(height|top)|offsetTop/)
assert.match(mobileSource, /if \(!home\) return/)
assert.match(mobileSource, /home\.style\.setProperty\('--m-home-height'/)
assert.doesNotMatch(mobileSource, /visualViewport\?\.addEventListener\('scroll'/)
assert.equal(context.mobileRouteForLocation({ hash: '', pathname: '/' }), '')
assert.equal(context.mobileRouteForLocation({ hash: '#essay', pathname: '/' }), 'essay')
assert.equal(context.mobileRouteForLocation({ hash: '', pathname: '/essay/2020/11/14/test/' }), 'essay=essay%2F2020%2F11%2F14%2Ftest')
console.log('Document shell: stable first-release flow, locally sized home, locally aligned banner and inline article toolbar passed.')
const indexHTML = fs.readFileSync(require('node:path').join(__dirname, '../index.html'), 'utf8')
const aboutHTML = fs.readFileSync(require('node:path').join(__dirname, '../about/index.html'), 'utf8')
const releaseVersion = aboutHTML.match(/网站版本：(\d{8}-\d{2})/)[1]
assert.ok(indexHTML.includes('/css/mobile.css?v=' + releaseVersion))
assert.ok(indexHTML.includes('/js/mobile-app.js?v=' + releaseVersion))
assert.match(indexHTML, /name="viewport" content="width=device-width, initial-scale=1\.0"/)
assert.doesNotMatch(indexHTML, /viewport-fit|name="theme-color"/)
assert.doesNotMatch(mobileSource, /themeColor|createElement\('meta'\)/)
assert.match(mobileSource, /load\('\/about\/index\.html\?v=' \+ encodeURIComponent\(jsVersion\)\)/)
console.log('About release version matches CSS and JS resource versions: ' + releaseVersion)
const baselineIndex = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-first/index.html'), 'utf8')
const baselineCSS = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-first/mobile.css'), 'utf8')
const baselineDesktopCSS = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-first/desktop.css'), 'utf8')
assert.ok(baselineDesktopCSS.includes("@import url('/css/markdown.css')"))
assert.ok(baselineDesktopCSS.includes("@import url('/css/min/mixxopost.min.css')"))
assert.match(baselineIndex, /name="viewport" content="width=device-width, initial-scale=1\.0"/)
assert.doesNotMatch(baselineIndex, /viewport-fit|name="theme-color"/)
assert.match(baselineCSS, /\.m-article\s*\{\s*padding: 54px/)
assert.doesNotMatch(baselineCSS, /#mobileApp\s*\{[^}]*position: fixed/)
for (const selector of ['html', 'body', '#mobileApp', '.m-article ._banner']) {
    const rule = new RegExp('(?:^|\\n)' + selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*\\{([^}]*)\\}')
    assert.equal(mobileCSS.match(rule)[1], baselineCSS.match(rule)[1], 'Original rule retained: ' + selector)
}
console.log('First-release comparison fixture retains its original viewport and article top gap.')
const nativeIndex = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-native/index.html'), 'utf8')
const nativeSource = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-native/article.js'), 'utf8')
assert.doesNotMatch(nativeIndex, /<link|mobile-app|1366\.css|position:\s*(fixed|sticky)|overflow(?:-[xy])?:/)
assert.match(nativeIndex, /viewport-fit=cover/)
assert.match(nativeIndex, /<meta name="viewport"[^>]*viewport-fit=cover/)
assert.doesNotMatch(nativeIndex, /html\s*\{|querySelector\('meta\[name="viewport"\]'\)/)
assert.match(nativeIndex, /repeating-linear-gradient/)
assert.match(nativeSource, /article\.replaceChildren/)
const nativeVersion = nativeIndex.match(/独立对照版本：(\d{8}-\d{2})/)[1]
assert.ok(aboutHTML.includes('/diagnostics/ios-native/?v=' + nativeVersion))
console.log('Independent Safari control has no app shell, fixed chrome or nested scrolling.')
