const assert = require('node:assert/strict')
const fs = require('node:fs')
const vm = require('node:vm')
const context = {}
vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname, '../js/mobile-app.js'), 'utf8'), context)
const metrics = context.mobileViewportMetrics
const expanded = metrics({ scale: 1, height: 640, offsetTop: 0 }, 812, 44, 34)
const collapsed = metrics({ scale: 1, height: 760, offsetTop: 0 }, 812, 44, 34)
assert.equal(expanded.height, 640)
assert.equal(collapsed.height, 760)
assert.ok(expanded.homeScale < collapsed.homeScale)
for (const height of [320, 480, 568, 640, 812]) {
    const result = metrics({ scale: 1, height, offsetTop: 0 }, 812, 44, 34)
    assert.ok(result.homeScale * 640 + 44 + 34 + 40 <= height + 0.001)
}
assert.equal(metrics({ scale: 1, height: 360, offsetTop: 150 }, 812).height, 360)
assert.equal(metrics({ scale: 2, height: 320, offsetTop: 80 }, 812).height, 812)
assert.equal(metrics(null, 568).height, 568)
assert.equal(metrics({ scale: 1, height: 900, offsetTop: 0 }, 900).homeScale, 1)
const points = [0, 100, 200]
const target = [4, 96, 204]
context.mobileTriangleStep(points, target, 16)
assert.ok(points[0] > 0 && points[0] < 4)
assert.ok(points[1] < 100 && points[1] > 96)
for (let frame = 0; frame < 240; frame++) context.mobileTriangleStep(points, target, 16)
assert.ok(Math.abs(points[0] - 4) < 0.1)
assert.ok(Math.abs(points[1] - 96) < 0.1)
console.log('Mobile layout: home sizing, safe areas, zoom, fallback and smooth triangle interpolation passed.')
const mobileCSS = fs.readFileSync(require('node:path').join(__dirname, '../css/mobile.css'), 'utf8')
assert.match(mobileCSS, /(?:^|\n)html\s*\{[^}]*height: auto;/)
assert.match(mobileCSS, /(?:^|\n)body\s*\{[^}]*background: white;/)
assert.match(mobileCSS, /(?:^|\n)#mobileApp\s*\{[^}]*min-height: 100svh;[^}]*overflow-x: clip;/)
assert.doesNotMatch(mobileCSS, /m-document-scroll|--m-viewport-(height|top)/)
assert.doesNotMatch(mobileCSS, /(?:^|\n)#mobileApp\s*\{[^}]*(?:position: fixed|height:\s*(?:100%|var\())/)
assert.match(mobileCSS, /\.m-home\s*\{[^}]*height: var\(--m-home-height, 100svh\);[^}]*overflow: hidden;/)
assert.doesNotMatch(mobileCSS, /\.m-detail > main\s*\{[^}]*overflow/)
assert.match(mobileCSS, /#mobileApp \.m-article > \.essay-title, #mobileApp \.m-article > \._date\s*\{\s*width: auto;/)
assert.doesNotMatch(mobileCSS, /m-detail-banner[^{}]*\{[^}]*position:\s*(fixed|sticky)/)
assert.doesNotMatch(mobileCSS, /m-detail-banner::(?:before|after)/)
assert.match(mobileCSS, /\.m-article\s*\{\s*padding: 54px/)
assert.match(mobileCSS, /\.m-article:has\(> \._banner\)\s*\{\s*padding-top: 0;/)
assert.match(mobileCSS, /\.m-article\s+\._banner::after\s*\{\s*content: none;/)
assert.doesNotMatch(mobileCSS, /\.m-article\s+\._banner\s*\{[^}]*position:\s*(?:fixed|sticky)/)
assert.match(mobileCSS, /\.m-article\s+\._banner\s*\{[^}]*height: 120px;/)
assert.doesNotMatch(mobileCSS, /\.m-article\s+\._banner::before/)
const mobileSource = fs.readFileSync(require('node:path').join(__dirname, '../js/mobile-app.js'), 'utf8')
const loadingMarkup = context.mobileLoadingMarkup()
const homeTriangle = fs.readFileSync(require('node:path').join(__dirname, '../assets/mobile/triangle.svg'), 'utf8')
assert.match(loadingMarkup, /role="status"[^>]*aria-live="polite"[^>]*aria-busy="true"/)
assert.match(loadingMarkup, /m-loading-label">正在加载/)
assert.equal((loadingMarkup.match(/<path /g) || []).length, 2)
for (const [, shape] of homeTriangle.matchAll(/ d="([^"]+)"/g)) assert.ok(loadingMarkup.includes('d="' + shape + '"'))
assert.doesNotMatch(loadingMarkup, /<img|Loading/)
assert.doesNotMatch(mobileSource, /Loading…/)
assert.match(mobileCSS, /\.m-loading\s*\{[^}]*min-height: 100svh;[^}]*display: grid;[^}]*place-items: center;/)
assert.match(mobileCSS, /\.m-loading-triangle\s*\{[^}]*width: 96px;/)
assert.match(mobileSource, /animateTriangle\(root\.querySelector\('\.m-loading-triangle'\), false\)/)
assert.match(mobileSource, /stopTriangle\(\)\s*\n\s*stopTriangle = \(\) => \{\}\s*\n\s*syncViewport\(\)/)
console.log('Mobile loading uses the inline home triangles, centered at reduced size with shared animation and accessible status.')
assert.match(mobileCSS, /\.m-article\s*\{[^}]*--m-article-font-scale: \.875;/)
assert.match(mobileCSS, /\.m-article \.essay-context\s*\{[^}]*min-width: 0;[^}]*font-size: calc\(16px \* var\(--m-article-font-scale\)\);[^}]*overflow-wrap: anywhere;/)
for (const selector of ['.m-article > .m-detail-bar', '.m-article .essay-context pre', '.m-article .essay-end-tip', '.m-article .essay-hr ._tags']) {
    const rule = new RegExp('(?:^|\\n)' + selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*\\{([^}]*)\\}')
    assert.match(mobileCSS.match(rule)[1], /font-size: calc\(\d+px \* var\(--m-article-font-scale\)\)/)
}
assert.doesNotMatch(mobileCSS, /\.m-article \.essay-context p\s*\{|\.m-article h[1-6][^{]*\{/)
assert.match(mobileCSS, /\.m-essay-card h2, \.m-article > \.essay-title\s*\{\s*font-size: 24px; line-height: 32px;/)
assert.match(mobileCSS, /\.m-essay-card \._date, \.m-article > \._date\s*\{\s*font-size: 16px; line-height: 22px;/)
assert.match(mobileCSS, /(?:^|\n)\.m-article > \._date\s*\{\s*display: block; margin-bottom: 17px;\s*\}/)
assert.doesNotMatch(mobileCSS, /\.m-article \.essay-context (?:h[1-6]|:is\(h1, h2, h3, h4, h5, h6\))\s*\{/)
assert.match(mobileCSS, /#mobileApp \.essay-context a\s*\{\s*color: #ff861e;/)
assert.match(mobileCSS, /\.m-article \.essay-context pre\s*\{[^}]*overflow-x: auto;[^}]*overflow-wrap: normal;/)
assert.match(mobileCSS, /\.m-article \.essay-context blockquote::after\s*\{[^}]*right: 10px;/)
assert.match(mobileCSS, /\.m-article \.essay-context \._youtube\s*\{[^}]*width: 100%;[^}]*aspect-ratio: 16 \/ 9;/)
assert.match(mobileSource, /querySelectorAll\('\.essay-context pre'\)\.forEach\(el => \{ if \(window\.hljs\) hljs\.highlightBlock\(el\)/)
assert.doesNotMatch(mobileSource, /querySelectorAll\('pre code'\)/)
console.log('Mobile article titles and dates share list typography; body text, headings, colors and highlighting remain unchanged.')
assert.match(mobileSource, /<time class="_date">/)
assert.match(mobileSource, /<h2 class="essay-title">/)
assert.match(mobileSource, /<div class="summary m-summary"><p>/)
assert.match(mobileCSS, /\.m-essay-card\s*\{[^}]*margin-bottom: 56px;[^}]*font-size: 16px;[^}]*line-height: 22px;[^}]*overflow-wrap: anywhere;/)
assert.match(mobileCSS, /\.m-essay-card h2\s*\{\s*margin: 10px 0 0;/)
assert.match(mobileCSS, /\.m-essay-card \.m-summary\s*\{[^}]*font-size: 22px; line-height: 30px;/)
const desktopCSS = fs.readFileSync(require('node:path').join(__dirname, '../css/1366.css'), 'utf8')
const desktopFontFamily = desktopCSS.match(/(?:^|\n)\s*html\s*\{[^}]*font-family:\s*([^;]+);/)[1]
const mobileSummaryRule = mobileCSS.match(/\.m-essay-card \.m-summary\s*\{([^}]+)\}/)[1]
assert.equal(mobileSummaryRule.match(/font-family:\s*([^;]+);/)[1], desktopFontFamily)
assert.match(mobileSummaryRule, /font-weight: 100;/)
assert.match(desktopCSS, /(?:^|\n)\s*\.summary\s*\{[^}]*font-weight: lighter;/)
console.log('Mobile list summaries use the desktop font family and computed weight without changing size or spacing.')
assert.match(mobileCSS, /\.m-essay-card \.m-preview\s*\{[^}]*height: 80px; margin-top: 22px;/)
assert.match(mobileCSS, /\.m-essay-list \.m-pagination\s*\{[^}]*font-size: 14px; line-height: 20px;/)
assert.match(mobileCSS, /\.m-essay-card \.m-summary p\s*\{[^}]*-webkit-line-clamp: 2;/)
assert.doesNotMatch(mobileCSS, /\.m-essay-card(?: time| p| h2)[^{]*\{[^}]*(?:font-weight|color):/)
console.log('Mobile essay lists enlarge dates, titles, summaries and pagination with matching spacing and two-line summaries.')
// Render the production list template for boundary pages without starting the app.
const listSandbox = { state: { page: 1 }, header: () => '', icon: () => '', routeFor: () => '', escape: value => value }
const listStart = mobileSource.indexOf('    function listEssays(posts) {')
const listEnd = mobileSource.indexOf('\n    function listGallery()', listStart)
assert.ok(listStart >= 0 && listEnd > listStart)
vm.runInNewContext(mobileSource.slice(listStart, listEnd), listSandbox)
assert.match(listSandbox.listEssays([]), /data-action="prev-page" hidden disabled/)
for (const page of [2, 9]) {
    listSandbox.state.page = page
    assert.doesNotMatch(listSandbox.listEssays([]), /data-action="prev-page" (?:hidden|disabled)/)
    assert.ok(listSandbox.listEssays([]).includes('<span>' + page + ' / 9</span>'))
}
assert.match(listSandbox.listEssays([]), /data-action="next-page" disabled/)
assert.match(mobileCSS, /\.m-pagination\s*\{[^}]*display: grid;[^}]*grid-template-columns: minmax\(0, 1fr\) auto minmax\(0, 1fr\);/)
assert.match(mobileCSS, /\.m-pagination > span\s*\{\s*grid-column: 2;/)
console.log('Pagination hides previous on page one while keeping the page number centered and next aligned right.')
assert.doesNotMatch(mobileSource, /banner\.remove\(\)|bannerHTML/)
assert.match(mobileSource, /doc\.body\.innerHTML \+ toolbar\(post, next\) \+ '<\/main>'/)
assert.doesNotMatch(mobileSource, /m-document-scroll|root\.style\.setProperty|--m-viewport-(height|top)|offsetTop/)
assert.match(mobileSource, /if \(!home\) return/)
assert.match(mobileSource, /home\.style\.setProperty\('--m-home-height'/)
assert.doesNotMatch(mobileSource, /visualViewport\?\.addEventListener\('scroll'/)
assert.equal(context.mobileRouteForLocation({ hash: '', pathname: '/' }), '')
assert.equal(context.mobileRouteForLocation({ hash: '#essay', pathname: '/' }), 'essay')
assert.equal(context.mobileRouteForLocation({ hash: '', pathname: '/essay/2020/11/14/test/' }), 'essay=essay%2F2020%2F11%2F14%2Ftest')
const percentPath = 'essay/2021/04/04/性能强劲的电脑 70%-90%完全体'
const percentURL = context.mobileContentURL(percentPath)
assert.ok(percentURL.includes('70%25-90%25'))
assert.equal(decodeURIComponent(percentURL), '/' + percentPath + '/context.html')
assert.equal(new URL(percentURL, 'https://mianxiu.me').search, '')
assert.match(mobileSource, /load\(mobileContentURL\(path\)\)/)
assert.doesNotMatch(mobileSource, /load\('\/' \+ path \+ '\/context\.html'\)/)
for (const title of ['中文 空格', 'literal %25', 'title #hash?query&value', 'plain-title']) {
    const path = 'essay/2021/04/04/' + title
    const url = new URL(context.mobileContentURL(path), 'https://mianxiu.me')
    assert.equal(decodeURIComponent(url.pathname), '/' + path + '/context.html')
    assert.equal(url.search, '')
    assert.equal(url.hash, '')
}
console.log('Article content URLs encode literal percent signs, spaces, Chinese and reserved title characters without changing routes.')
console.log('Document shell: stable first-release flow, locally sized home, locally aligned banner and inline article toolbar passed.')
const indexHTML = fs.readFileSync(require('node:path').join(__dirname, '../index.html'), 'utf8')
const aboutHTML = fs.readFileSync(require('node:path').join(__dirname, '../about/index.html'), 'utf8')
const cssVersion = indexHTML.match(/\/css\/mobile\.css\?v=(\d{8}-\d{2})/)[1]
const jsVersion = indexHTML.match(/\/js\/mobile-app\.js\?v=(\d{8}-\d{2})/)[1]
assert.equal(cssVersion, jsVersion)
assert.doesNotMatch(aboutHTML, /site-version|网站版本|本次更新|diagnostics\/ios/)
assert.doesNotMatch(mobileSource, /当前页面资源版本|CSS：|JS：/)
assert.match(indexHTML, /name="viewport" content="width=device-width, initial-scale=1\.0, viewport-fit=cover"/)
assert.doesNotMatch(indexHTML, /name="theme-color"/)
assert.doesNotMatch(mobileSource, /themeColor|createElement\('meta'\)/)
assert.match(mobileSource, /load\('\/about\/index\.html\?v=' \+ encodeURIComponent\(jsVersion\)\)/)
console.log('About is free of temporary diagnostics; internal CSS/JS cache versions match.')
const baselineIndex = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-first/index.html'), 'utf8')
const baselineCSS = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-first/mobile.css'), 'utf8')
const baselineDesktopCSS = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-first/desktop.css'), 'utf8')
assert.ok(baselineDesktopCSS.includes("@import url('/css/markdown.css')"))
assert.ok(baselineDesktopCSS.includes("@import url('/css/min/mixxopost.min.css')"))
assert.match(baselineIndex, /name="viewport" content="width=device-width, initial-scale=1\.0"/)
assert.doesNotMatch(baselineIndex, /viewport-fit|name="theme-color"/)
assert.match(baselineCSS, /\.m-article\s*\{\s*padding: 54px/)
assert.doesNotMatch(baselineCSS, /#mobileApp\s*\{[^}]*position: fixed/)
for (const selector of ['html', 'body', '#mobileApp', '.m-article ._banner']) {
    const rule = new RegExp('(?:^|\\n)' + selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*\\{([^}]*)\\}')
    assert.equal(mobileCSS.match(rule)[1], baselineCSS.match(rule)[1], 'Original rule retained: ' + selector)
}
console.log('First-release comparison fixture retains its original viewport and article top gap.')
const nativeIndex = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-native/index.html'), 'utf8')
const nativeSource = fs.readFileSync(require('node:path').join(__dirname, '../diagnostics/ios-native/article.js'), 'utf8')
assert.doesNotMatch(nativeIndex, /<link|mobile-app|1366\.css|position:\s*(fixed|sticky)|overflow(?:-[xy])?:/)
assert.match(nativeIndex, /viewport-fit=cover/)
assert.match(nativeIndex, /<meta name="viewport"[^>]*viewport-fit=cover/)
assert.doesNotMatch(nativeIndex, /html\s*\{|querySelector\('meta\[name="viewport"\]'\)/)
assert.match(nativeIndex, /repeating-linear-gradient/)
assert.match(nativeSource, /article\.replaceChildren/)
assert.match(nativeIndex, /独立对照版本：\d{8}-\d{2}/)
console.log('Independent Safari control has no app shell, fixed chrome or nested scrolling.')
